global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'jenkins'
    static_configs:
      - targets: ['52.90.147.63:8080']
    metrics_path: '/prometheus'
```[_{{{CITATION{{{_1{Jenkins Monitoring with Prometheus and Grafana Dashboard - ğ”»ğ•–ğ•§ ...](https://www.devopsart.com/2019/09/jenkins-monitoring-with-prometheus-and.html)

